# Generated by Django 2.1.3 on 2018-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('area_unit', models.CharField(default='', max_length=10, null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('bedrooms', models.PositiveIntegerField(null=True)),
                ('home_size', models.PositiveIntegerField(null=True)),
                ('home_type', models.CharField(default='', max_length=100, null=True)),
                ('last_sold_date', models.DateField(null=True)),
                ('last_sold_price', models.PositiveIntegerField(null=True)),
                ('link', models.CharField(default='', max_length=100, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('property_size', models.PositiveIntegerField(null=True)),
                ('rent_price', models.PositiveIntegerField(null=True)),
                ('rentzestimate_amount', models.PositiveIntegerField(null=True)),
                ('rentzestimate_last_updated', models.DateField(null=True)),
                ('tax_value', models.PositiveIntegerField(null=True)),
                ('tax_year', models.PositiveIntegerField(null=True)),
                ('year_built', models.PositiveIntegerField(null=True)),
                ('zestimate_amount', models.PositiveIntegerField(null=True)),
                ('zestimate_last_updated', models.DateField(null=True)),
                ('zillow_id', models.PositiveIntegerField(null=True)),
                ('address', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=100, null=True)),
                ('state', models.CharField(default='', max_length=2, null=True)),
                ('zipcode', models.CharField(default='', max_length=10, null=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
